// RUN: %libomp-compile-and-run | FileCheck %s
// REQUIRES: ompt


#include "callback.h"


#define DELAY 1000000
#define COUNT 10

// burn some CPU cycles
void burn_CPU(int count) {
  int j, k;
  volatile float x;
  int jmax;

  jmax = 7 * count;

  for (j = 0; j < jmax; j++) {
    x = 0;
    for (k = 0; k < DELAY; k++) {
      x = x + 1.0;
    }
  }
}

int main() {
#pragma omp parallel num_threads(2)
  {
    burn_CPU(COUNT);
  }

  // Check if libomp supports the callbacks for this test.
  // CHECK-NOT: {{^}}0: Could not register callback 'ompt_callback_parallel_begin'
  // CHECK-NOT: {{^}}0: Could not register callback 'ompt_callback_parallel_end'


  // CHECK: {{^}}0: NULL_POINTER=[[NULL:.*$]]
  // CHECK: {{^}}[[MASTER_ID:[0-9]+]]: ompt_event_initial_task_begin

  // CHECK: {{^}}[[MASTER_ID]]: ompt_event_parallel_begin
  // CHECK-SAME: parallel_id=[[PARALLEL_ID_1:[0-9]+]]
  // CHECK-SAME: invoker=2

  // CHECK: {{^}}[[MASTER_ID]]: ompt_event_parallel_end
  // CHECK-SAME: parallel_id=[[PARALLEL_ID_1:[0-9]+]]
  // CHECK-SAME: invoker=2


  // Consider the callstacks of the master thread while executing the burn_CPU
  // function when the code is generated by gcc and clang respectively:
  // 1) gcc used to generate the code
        // #0  burn_CPU (count=10)
        // #1  0x0000000000402b8b in main._omp_fn.0 ()
        // #2  0x00007ffff7b601f8 in __kmp_api_GOMP_parallel
        // #3  0x0000000000402b6e in main ()
  // 2) clang is used to generate the code.
        // #0  burn_CPU (count=10)
        // #1  0x000000000040325a in .omp_outlined._debug__
        // #2  0x000000000040327d in .omp_outlined.
        // #3  0x00007ffff7b862c3 in __kmp_invoke_microtask
        // #4  0x00007ffff7acac6e in __kmp_invoke_task_func
        // #5  0x00007ffff7abea3d in __kmp_fork_call
        // #6  0x00007ffff7aa7930 in __kmpc_fork_call
        // #7  0x0000000000403231 in main ()
  // One can notice that, no matter what compiler of the previous two is used,
  // the outlined function that corresponds to the implicit tasks is invoked
  // by the runtime. So the invoker should take value of
  // ompt_parallel_invoker_runtime==2


  return 0;
}
